name: Mention All Bot Heroku Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ""
          heroku_app_name: ""
          heroku_email: ""
        env:
          HD_APP_ID: ${{secrets.APP_ID}}
          HD_API_HASH: ${{secrets.API_HASH}}
          HD_TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}
